
version: 2

models:
  - name: stg_climate_daily
    description: "climate dbt model"
    columns:
      - name: date
        tests: [not_null]
      - name: location_id
        tests: [not_null]

  - name: fact_climate_daily
    columns:
      - name: date
        tests: [not_null]
